#pragma once

#define EMULATOR_WINDOW_TITLE "CHIP-8 Emulator"

#define CHIP_8_MEMORY_SIZE 4096
#define CHIP_8_REGISTERS 16
#define CHIP_8_STACK_SIZE 16

#define CHIP_8_WIDTH 64
#define CHIP_8_HEIGHT 32
#define CHIP_8_WINDOW_MULTIPLIER 10
#define CHIP_8_WINDOW_WIDTH CHIP_8_WIDTH * CHIP_8_WINDOW_MULTIPLIER
#define CHIP_8_WINDOW_HEIGHT CHIP_8_HEIGHT * CHIP_8_WINDOW_MULTIPLIER